name: flutter_3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+1
  # flutter_3d_obj: ^0.0.2
  # flutter_3d: ^0.4.1
  http: ^1.2.1
  webview_flutter: ^4.8.0
  path_provider: ^2.0.3
  # permission_handler: ^12.1.0
  # flutter_cube: ^0.3.0
  video_player: ^2.3.2
  url_launcher: ^6.0.9
  flutter_blue:
  firebase_core: ^3.1.0  
  firebase_storage: ^12.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # flutter_video_player: ^0.2.1

flutter:
  uses-material-design: true

assets:
  - assets/image1.png
  - assets/image2.png
  - assets/undercarriage.stp
  - assets/billoraeder alle.mp4
  - assets/billo_raddrehen.glb
